#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1 
bspc config focused_border_color "#ff1493"
bspc config normal_border_color "#750843"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

vmware-user-suid-wrapper &

/usr/bin/feh --bg-fill ~/Pictures/wallpaper.png

~/.config/polybar/launch.sh

wmname LG3D &

picom &